
#################
###  GLOBALS  ###
#################

PLAYER_COUNT = 1
CURRENT_LEVEL = 0
GAME_JUST_STARTED = False
print('resetting GAME_JUST_STARTED')

BOARD_WIDTH  = 14 # cannot be less than 4
SINGLE_PLAYER_BOARD_WIDTH = 10
MULTI_PLAYER_BOARD_WIDTH = 14
BOARD_HEIGHT = 20 # should be about twice BOARD_WIDTH

WINDOW_HEIGHT = 800
WINDOW_WIDTH = 1000
BOARD_HEIGHT_BUFFER = 2
FRAME_RATE = 60

TILE_SIZE = min(WINDOW_WIDTH,WINDOW_HEIGHT) // max(BOARD_WIDTH,BOARD_HEIGHT)