# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['main.py',
              'client/client.py',
              'client/constants.py',
              'client/control.py',
              'client/globals.py',
              'client/states/game.py',
              'client/states/game_over_menu.py',
              'client/states/create_menu.py',
              'client/states/join_menu.py',
              'client/states/lobby_menu.py',
              'client/states/main_menu.py',
              'client/states/pause_menu.py',
              'client/states/state.py',
              'common/connection.py',
              'common/enums.py',
              'common/player_input.py',
              'common/components/piece.py',
              'common/components/player.py',
              'common/components/text.py',
              'common/components/tile.py',
              'resources/tile_maker.py',
              'server/clearing_line.py',
              'server/constants.py',
              'server/control.py',
              'server/globals.py',
              'server/server.py',
              'server/states/game.py',
              'server/states/lobby.py',
              'server/states/state.py'
              ],
             pathex=['C:\\Users\\Spencer\\Documents\\Tetrisn-t'],
             binaries=[],
             datas=[('resources/backgroundblock.bmp', './resources/'),
                    ('resources/iconsmall.bmp',       './resources/'),
                    ('resources/munro-small.ttf',     './resources/')],
             hiddenimports=['client'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='Tetrisn\'t',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False)
